# azure-pipelines.yml
trigger:
  branches:
    include:
      - main
      - master

stages:
  - stage: DeployApp
    displayName: "Deploy Application Code via Ansible"
    jobs:
      - job: App_Deployment
        displayName: "Run Ansible Playbook to Deploy App"
        pool:
          name: "Default"     # ✅ Use your self-hosted agent pool
          demands:
            - agent.name -equals Default

        variables:
          BACKEND_PRIVATE_IP: $(backend_private_ip)
          BACKEND_PORT: $(backend_port)
          FRONTEND_PORT: $(frontend_port)
          MYSQL_FQDN: $(mysql_fqdn)
          MYSQL_ADMIN_USERNAME: $(mysql_admin_username)
          MYSQL_ADMIN_PASSWORD: $(mysql_admin_password)
          MYSQL_DATABASE: $(mysql_database)

        steps:
          # Step 1: Clean and Checkout
          - checkout: self
            clean: true
            displayName: "Checkout repository"

          - script: |
              echo "Current working directory:"
              pwd
              echo "Listing repo root:"
              ls -la
            displayName: "Verify agent working directory"

          # Step 2: Ensure Ansible is installed on self-hosted agent
          - script: |
              echo "Installing Ansible if not present..."
              sudo apt-get update -y
              if ! command -v ansible >/dev/null 2>&1; then
                sudo apt-get install -y ansible sshpass
              else
                echo "Ansible already installed."
              fi
              ansible --version
            displayName: "Install/Verify Ansible & SSH dependencies"

          # Step 3: Download SSH Private Key
          - task: DownloadSecureFile@1
            name: download_ssh_key
            displayName: "Download SSH Private Key"
            inputs:
              secureFile: "id_rsa"

          # Step 4: Setup SSH Key
          - script: |
              mkdir -p ~/.ssh
              cp "$(download_ssh_key.secureFilePath)" ~/.ssh/id_rsa
              chmod 600 ~/.ssh/id_rsa
              echo "Host *" > ~/.ssh/config
              echo "  StrictHostKeyChecking no" >> ~/.ssh/config
              echo "  UserKnownHostsFile=/dev/null" >> ~/.ssh/config
              ls -la ~/.ssh
            displayName: "Setup SSH Key for Ansible Access"

          # Step 5: Validate Ansible folder and playbook
          - script: |
              echo "Validating Ansible directory..."
              cd app-epicbook/ansible
              echo "Current path: $(pwd)"
              echo "Contents:"
              ls -R
              echo "Previewing site.yml header:"
              head -n 20 site.yml
            displayName: "Verify Ansible Files Exist"

          # Step 6: Run Ansible Playbook
          - script: |
              echo "Running Ansible Playbook..."
              cd app-epicbook/ansible
              ansible-playbook -i inventory.ini site.yml \
                --extra-vars "\
                  backend_private_ip=$(BACKEND_PRIVATE_IP) \
                  backend_port=$(BACKEND_PORT) \
                  frontend_port=$(FRONTEND_PORT) \
                  mysql_fqdn=$(MYSQL_FQDN) \
                  mysql_admin_username=$(MYSQL_ADMIN_USERNAME) \
                  mysql_admin_password=$(MYSQL_ADMIN_PASSWORD) \
                  mysql_database=$(MYSQL_DATABASE)" \
                --ssh-extra-args "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" -vv
            displayName: "Run Ansible Playbook"
            env:
              ANSIBLE_HOST_KEY_CHECKING: "False"