stages:
  - stage: DeployApp
    displayName: "Deploy Application Code via Ansible"
    jobs:
      - job: App_Deployment
        displayName: "Run Ansible Playbook to Deploy App"
        pool:
          name: "Default"
        variables:
          BACKEND_PRIVATE_IP: $(backend_private_ip)
          BACKEND_PORT: $(backend_port)
          FRONTEND_PORT: $(frontend_port)
          MYSQL_FQDN: $(mysql_fqdn)
          MYSQL_ADMIN_USERNAME: $(mysql_admin_username)
          MYSQL_ADMIN_PASSWORD: $(mysql_admin_password)
          MYSQL_DATABASE: $(mysql_database)
        steps:
          - checkout: self
            clean: true
            fetchDepth: 1
          - script: |
              echo "Cleaning any cached Ansible files..."
              rm -rf /home/azureuser/myagent/_work/3/s/app-epicbook/ansible/roles/common/tasks/main.yml
              rm -rf ~/.ansible
              ls -la app-epicbook/ansible/roles/common/tasks/
              cat app-epicbook/ansible/roles/common/tasks/main.yml
            displayName: "Clean cached files and verify"
          - script: |
              sudo apt update
              sudo apt install -y ansible sshpass
            displayName: "Install Ansible & SSH dependencies"
          - task: DownloadSecureFile@1
            name: download_ssh_key
            inputs:
              secureFile: "id_rsa"
          - script: |
              mkdir -p ~/.ssh
              cp $(download_ssh_key.secureFilePath) ~/.ssh/id_rsa
              chmod 600 ~/.ssh/id_rsa
              echo "StrictHostKeyChecking no" > ~/.ssh/config
            displayName: "Setup SSH Private Key"
          - script: |
              cd app-epicbook/ansible
              ansible-playbook -i inventory.ini site.yml \
                --extra-vars "backend_private_ip=$(BACKEND_PRIVATE_IP) backend_port=$(BACKEND_PORT) frontend_port=$(FRONTEND_PORT) mysql_fqdn=$(MYSQL_FQDN) mysql_admin_username=$(MYSQL_ADMIN_USERNAME) mysql_admin_password=$(MYSQL_ADMIN_PASSWORD) mysql_database=$(MYSQL_DATABASE)" \
                --ssh-extra-args "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" -v
            displayName: "Run Ansible Playbook"
            env:
              ANSIBLE_HOST_KEY_CHECKING: "False"
